### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by dackers86** [gridws/grid-cms-extension#1]
Hello

For the https://extension.dev website requires extension to have a suitable amount of documentation for users to read on the website.

Before official publication, would it be possible to update the `PREINSTALL` and `POSTINSTALL` documentation to include more detail before official publication.

**Comment by okydk** [comment]
Sure, I've added the essential docs. Will this be sufficient? :)

**Comment by dackers86** [comment]
Great, thanks! All looks good, for additional context. Could you add a billing section at the bottom the pre-install.

We have an example [here](https://github.com/firebase/extensions/blob/next/firestore-translate-text/PREINSTALL.md)

Once that is added it should be good to go 👍🏻
